<div
    class="max-h-72 min-h-[8rem] overflow-y-auto px-4 py-3 text-sm"
    role="log"
    aria-live="polite"
    data-guest-assistant-thread
>
    @if (count($thread) === 0)
        <p class="text-neutral-500 dark:text-neutral-400">
            {{ __('Start a conversation — replies are generated by AI.') }}
        </p>
    @else
        <ul class="flex flex-col gap-3">
            @foreach ($thread as $row)
                <li
                    class="flex @if ($row['role'] === 'user') justify-end @else justify-start @endif"
                    wire:key="thread-{{ $loop->index }}"
                >
                    <div
                        class="max-w-[90%] rounded-2xl px-3 py-2 text-sm leading-relaxed @if ($row['role'] === 'user') bg-[#1b1b18] text-white dark:bg-[#eeeeec] dark:text-[#1C1C1A] @else border border-[#e3e3e0] bg-white text-[#1b1b18] dark:border-[#3E3E3A] dark:bg-[#0a0a0a] dark:text-[#EDEDEC] @endif"
                    >
                        {{ $row['content'] }}
                    </div>
                </li>
            @endforeach
        </ul>
    @endif
</div>
