<div
    x-ref="threadRoot"
    class="scrollbar-thin max-h-72 min-h-[8rem] overflow-y-auto px-4 py-3 text-sm"
    role="log"
    aria-live="polite"
    data-guest-assistant-thread
>
    <ul class="flex flex-col gap-3">
        @forelse ($thread as $row)
            <li
                class="flex @if ($row['role'] === 'user') justify-end @else justify-start @endif"
                wire:key="thread-{{ $loop->index }}"
            >
                <div
                    class="max-w-[90%] rounded-2xl px-3 py-2 text-sm leading-relaxed @if ($row['role'] === 'user') bg-[#1b1b18] text-white dark:bg-[#eeeeec] dark:text-[#1C1C1A] @else border border-[#e3e3e0] bg-white text-[#1b1b18] dark:border-[#3E3E3A] dark:bg-[#0a0a0a] dark:text-[#EDEDEC] @endif"
                >
                    @if ($row['role'] === 'assistant')
                        <div class="guest-assistant-markdown">
                            {!! \App\Ai\Agents\GuestAssistant::renderAssistantMessageHtml($row['content']) !!}
                        </div>
                    @else
                        {{ $row['content'] }}
                    @endif
                </div>
            </li>
        @empty
            <li class="list-none" x-show="! optimisticUser">
                <p class="text-neutral-500 dark:text-neutral-400">
                    {{ __('Start a conversation — replies are generated by AI.') }}
                </p>
            </li>
        @endforelse

        <li class="flex justify-end" x-show="optimisticUser">
            <div
                class="max-w-[90%] rounded-2xl bg-[#1b1b18] px-3 py-2 text-sm leading-relaxed text-white dark:bg-[#eeeeec] dark:text-[#1C1C1A]"
                x-text="optimisticUser"
            ></div>
        </li>

        <li class="flex justify-start" wire:loading wire:target="send">
            <div
                class="flex items-center gap-0.5 py-1"
                role="status"
                aria-label="{{ __('Agent is typing') }}"
            >
                <span class="sr-only">{{ __('Agent is typing') }}</span>
                <span
                    class="inline-block h-1.5 w-1.5 animate-bounce rounded-full bg-neutral-400 opacity-80 [animation-delay:-0.3s] dark:bg-neutral-500"
                    aria-hidden="true"
                ></span>
                <span
                    class="inline-block h-1.5 w-1.5 animate-bounce rounded-full bg-neutral-400 opacity-80 [animation-delay:-0.15s] dark:bg-neutral-500"
                    aria-hidden="true"
                ></span>
                <span
                    class="inline-block h-1.5 w-1.5 animate-bounce rounded-full bg-neutral-400 opacity-80 dark:bg-neutral-500"
                    aria-hidden="true"
                ></span>
            </div>
        </li>
    </ul>
</div>
